- pages/team.html
Change alt to reflect where link was going
Updated two links.
> Alt and 2 links

- assets/css/general.css
I get a horizontal scrollbar on the website. This seems to fix it without (I hope) any side effects.
> Remove padding to fix horizontal scrollbar

- assets/js/main.js
- pages/_includes/layouts/default.njk
Reverts openwebdocs/owd-website#8
> Revert "Use only prefers-color-scheme for theming"

- pages/team.html
Dan got a fancy new job, update affiliation.
> Change Torgo's affiliation

- pages/index.html
Fix https://github.com/openwebdocs/owd-website/issues/23
Also removed Coil
> Sort sponsors alphabetically

- pages/_includes/layouts/default.njk
I think I was blind when I did that previous PR. 
I added the image URL to all tags for some reason. This removes them because I don't think we need them all.
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fopenwebdocs.org is a debugging tool that I found.
> Fix og meta tags

- pages/_includes/layouts/default.njk
meta description was empty actually, so maybe that's not really liked by twitter
> Add more OG meta tags, fix meta description

- assets/css/general.css
- pages/index.html
I have added the link to the sponsors header in the landing page, below is the video of how that link works!
https://user-images.githubusercontent.com/94648837/189400785-fa502173-be2d-44c0-b8bd-169a7f727717.mov
> Add the link to the sponsors header in the landing page.

- pages/content/posts/apple-joins-sc.md
Copied from our Open Collect page.
> Add Open Collect post about Apple joining the SC to the blog

- assets/css/general.css
Make the dates italic and offset the color a bit.
> Blog date appearance

- pages/sponsors.html
Fixes https://github.com/openwebdocs/owd-website/issues/43.
> Thank individual sponsors

- assets/css/general.css
- assets/css/theme.css
- pages/content/posts/2022-q3-report/index.md
This is just a suggestion to try out.
* I don't think we should use a blockquote for the callout, since it isn't a quote. The simplest thing to do is what I've done here, which is to go into HTML and make it `<div class="callout">`.
* I don't love the border for emphasis. Here I've used a background instead. I chose the colors from the swoosh on the homepage.
I also think the callout has too much vertical padding but I didn't try to fix that here.
> try a different callout style

- pages/team.html
@bsmith pointed out that a sentence was accidentally broken up into two, but should stay one!
> Update my biography

- pages/content/posts/web-api-page-titles/index.md
Fixes https://github.com/openwebdocs/owd-website/issues/73.
> Fix issue 73: Improve alt text

- pages/team.html
> Add mastodon for Jean-Yves and Florian

- assets/css/general.css
Introduced in https://github.com/openwebdocs/owd-website/pull/71
Breaks https://openwebdocs.org/sponsors/ however
> Remove img width: 100%

- pages/content/posts/secure-the-web-forward.md
@wbamberg quick write up about last week, please take it apart and make it great :)
> Add post: Docs to Secure the Web Forward

- pages/content/posts/thanks-2023.md
Prettier was not intentional but I think is fine?
> Add a missing period, also Prettier apparently

- pages/_includes/layouts/default.njk
See https://mastodon-link-debugger.vercel.app/profile/@OpenWebDocs@front-end.social
> Add rel=me for mastodon verification

- pages/team.html
- Add Igalia to the list of GC orgs
- Change my title
We can make this page a lot better, I think, but these are some quick fixes for now.
> Update team page

- pages/content/posts/css-containment.md
new blog post for the containment pages I did.
> new containment blog post

- pages/team.html
happy to accept feedback on this!
> Update wbamberg's bio

- pages/content/reports/2024/index.md
As we discussed, just worked on this part for framing & adding the numbers. Also referred to staff reduction.
> Update project financials part!
